theme: just-the-docs
title: CellRex Documentation
description: Documentation for biological file sorting and metadata enrichment
baseurl: "/Ca2-ImageUtils"
url: "https://twinsten.github.io"

# Navigation
aux_links:
  "View on GitHub":
    - "//github.com/twinsten/Ca2-ImageUtils"

# Search
search_enabled: true